'use client';

import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { CreditCard, Smartphone } from 'lucide-react';
import { loanAPI, paymentAPI, mobileMoneyAPI } from '@/lib/api';

export default function PaymentsPage(){
 const router=useRouter();
 const [loans,setLoans]=useState<any[]>([]);const [loanId,setLoanId]=useState('');const [amount,setAmount]=useState('');const [method,setMethod]=useState('MPESA');const [phone,setPhone]=useState('');const [msg,setMsg]=useState('');const [busy,setBusy]=useState(false);
 useEffect(()=>{const raw=localStorage.getItem('user');const token=localStorage.getItem('token');if(!token||!raw){router.push('/login');return;}try{const u=JSON.parse(raw);if(u.role!=='BORROWER'){router.push(u.role==='BURSER'?'/bursar':u.role==='LENDER'?'/lender':'/dashboard');return;}const q=new URLSearchParams(window.location.search).get('loanId');if(q)setLoanId(q);(async()=>{try{const r=await loanAPI.byBorrower();setLoans(r.data?.data||r.data||[])}catch(e){setMsg('Imeshindikana kupakia mikopo.')}})()}catch{router.push('/login')}},[router]);
 const pay=async(e:any)=>{e.preventDefault();setBusy(true);setMsg('');try{const p=await paymentAPI.create({loanId:Number(loanId),amount:Number(amount),paymentMethod:method});const payment=p.data?.data||p.data;if(['MPESA','MIXX_BY_YAS','AIRTEL_MONEY','HALOPESA','TANQR','TIPS','TISS'].includes(method)){const r=await mobileMoneyAPI.checkout(payment.id,phone);const data=r.data?.data||r.data;setMsg(data?.message||('Gateway status: '+data?.status));}else{setMsg('Malipo yameandikwa PENDING. Bursar/Lender atayalinganisha na kuthibitisha baada ya kuona cash au bank transaction. Reference ya mfumo: '+payment.transactionId);}}catch(e:any){setMsg(e?.response?.data?.message||'Malipo yameshindwa kuanzishwa.')}finally{setBusy(false)}};
 return <main className="min-h-screen bg-slate-50 p-6 dark:bg-slate-950"><div className="mx-auto max-w-3xl space-y-6">
  <section className="rounded-3xl bg-white p-6 shadow-sm dark:bg-slate-900"><div className="mb-4 flex justify-end"><button type="button" onClick={()=>window.history.back()} className="rounded-xl border px-4 py-2 text-sm font-bold">← Rudi nyuma</button></div><div className="flex items-center gap-3"><div className="rounded-xl bg-emerald-50 p-3 text-emerald-600"><CreditCard/></div><div><h1 className="text-2xl font-black">Malipo ya Mkopo</h1><p className="text-sm text-slate-500">M-Pesa, Mixx by Yas, Airtel Money, HaloPesa, TANQR, TIPS na TISS. Mfumo hutenganisha channel/rail na reconciliation ya lender/bursar.</p></div></div></section>
  <form onSubmit={pay} className="space-y-4 rounded-3xl bg-white p-6 shadow-sm dark:bg-slate-900"><select required value={loanId} onChange={e=>setLoanId(e.target.value)} className="w-full rounded-xl border p-3 dark:border-slate-700 dark:bg-slate-950"><option value="">Chagua loan</option>{loans.filter(l=>!['PAID','REJECTED'].includes(l.status)).map(l=><option key={l.id} value={l.id}>Loan #{l.id} · TZS {l.amount} · {l.status}</option>)}</select>
  <div className="rounded-2xl border border-blue-200 bg-blue-50 p-4 text-sm dark:border-blue-900 dark:bg-blue-950/30">Chagua loan kisha mfumo utahesabu salio lake kutoka kwenye payments zilizothibitishwa. Usilipe zaidi ya salio linalodaiwa.</div><input required type="number" min="1" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="Kiasi cha kulipa" className="w-full rounded-xl border p-3 dark:border-slate-700 dark:bg-slate-950"/>
  <select value={method} onChange={e=>setMethod(e.target.value)} className="w-full rounded-xl border p-3 dark:border-slate-700 dark:bg-slate-950">{['MPESA','MIXX_BY_YAS','AIRTEL_MONEY','HALOPESA','TANQR','TIPS','TISS','BANK_TRANSFER','CASH'].map(x=><option key={x}>{x}</option>)}</select>
  {['MPESA','MIXX_BY_YAS','AIRTEL_MONEY','HALOPESA'].includes(method)&&<input required value={phone} onChange={e=>setPhone(e.target.value)} placeholder="+2557XXXXXXXX" className="w-full rounded-xl border p-3 dark:border-slate-700 dark:bg-slate-950"/>}
  <div className="rounded-2xl bg-slate-50 p-4 text-sm text-slate-600 dark:bg-slate-950"><Smartphone className="mb-2 h-5 w-5"/>TANQR/TIPS/TISS na mobile-money hutegemea provider/rail configuration ya taasisi. Credentials hubaki server-side; Bursar anaona reconciliation na reference ya kila malipo.</div>
  <button disabled={busy} className="w-full rounded-xl bg-blue-600 px-4 py-3 font-bold text-white">{busy?'Inaanzisha...':'Lipa Sasa'}</button></form>{msg&&<div className="rounded-2xl bg-white p-4 text-sm dark:bg-slate-900">{msg}</div>}
 </div></main>;
}
