'use client';
import {useEffect,useState} from 'react';
import {useRouter} from 'next/navigation';
import {collateralAPI,loanAPI} from '@/lib/api';
const money=(v:any)=>new Intl.NumberFormat('sw-TZ',{style:'currency',currency:'TZS',maximumFractionDigits:0}).format(Number(v||0));
export default function CollateralPage(){
 const router=useRouter();const [loan,setLoan]=useState<any>(null),[records,setRecords]=useState<any[]>([]);
 const [type,setType]=useState('GARI'),[description,setDescription]=useState(''),[value,setValue]=useState('');
 const [photos,setPhotos]=useState<string[]>([]),[documents,setDocuments]=useState<{name:string,data:string}[]>([]);
 const [status,setStatus]=useState(''),[busy,setBusy]=useState(false),[viewing,setViewing]=useState<any>(null);
 const loanId=typeof window!=='undefined'?new URLSearchParams(window.location.search).get('loanId'):null;
 const load=async()=>{if(!loanId)return;try{const [l,r]=await Promise.all([loanAPI.get(Number(loanId)),collateralAPI.byLoan(Number(loanId))]);setLoan(l.data?.data??l.data);setRecords(r.data?.data??r.data??[])}catch(e:any){setStatus(e?.response?.data?.message||'Dhamana haijapatikana')}};
 useEffect(()=>{load()},[loanId]);
 const read=(file:File,cb:(x:string)=>void)=>{const r=new FileReader();r.onload=()=>cb(String(r.result));r.readAsDataURL(file)};
 const addPhotos=(e:any)=>Array.from(e.target.files||[]).slice(0,10).forEach((f:any)=>read(f,(d)=>setPhotos(p=>p.length<10?[...p,d]:p)));
 const addDocs=(e:any)=>Array.from(e.target.files||[]).slice(0,10).forEach((f:any)=>read(f,(d)=>setDocuments(p=>p.length<10?[...p,{name:f.name,data:d}]:p)));
 const save=async()=>{if(!loanId||!description.trim())return setStatus('Jaza maelezo ya dhamana.');setBusy(true);setStatus('');try{await collateralAPI.add(Number(loanId),{type,description,value:Number(value||0),photos,documents});setStatus('Dhamana, picha na nyaraka zimehifadhiwa.');setDescription('');setValue('');setPhotos([]);setDocuments([]);await load()}catch(e:any){setStatus(e?.response?.data?.message||'Dhamana haijahifadhiwa.')}finally{setBusy(false)}};
 const view=async(id:number)=>{try{const r=await collateralAPI.evidence(Number(loanId),id);setViewing(r.data?.data??r.data)}catch(e:any){setStatus(e?.response?.data?.message||'Evidence haijasomeka')}};
 return <main className="min-h-screen bg-slate-50 p-4 dark:bg-slate-950"><div className="mx-auto max-w-5xl space-y-5">
  <button onClick={()=>router.back()} className="rounded-xl border bg-white px-4 py-2 text-sm font-bold dark:bg-slate-900">← Rudi nyuma</button>
  <section className="rounded-3xl bg-white p-6 shadow-sm dark:bg-slate-900"><h1 className="text-2xl font-black">📸 Dhamana & Evidence</h1><p className="mt-1 text-sm text-slate-500">Loan #{loanId||'—'} · {loan?.borrower?.fullName||'—'} · {loan&&money(loan.amount)}</p><p className="mt-2 text-xs text-slate-500">Piga picha kwa camera ya kifaa na hifadhi nyaraka zote kwenye Loan ID.</p></section>
  {status&&<div className="rounded-2xl border bg-white p-4 text-sm font-semibold dark:bg-slate-900">{status}</div>}
  <section className="rounded-3xl border bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900">
   <div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold">Aina<select value={type} onChange={e=>setType(e.target.value)} className="mt-2 w-full rounded-xl border p-3 dark:border-slate-700 dark:bg-slate-950"><option>GARI</option><option>PIKIPIKI</option><option>NYUMBA</option><option>ARDHI</option><option>ELECTRONICS</option><option>SIMU</option><option>OTHER</option></select></label><label className="text-sm font-bold">Thamani (TZS)<input type="number" min="0" value={value} onChange={e=>setValue(e.target.value)} className="mt-2 w-full rounded-xl border p-3 dark:border-slate-700 dark:bg-slate-950"/></label></div>
   <label className="mt-4 block text-sm font-bold">Maelezo<textarea value={description} onChange={e=>setDescription(e.target.value)} className="mt-2 min-h-28 w-full rounded-xl border p-3 dark:border-slate-700 dark:bg-slate-950" placeholder="Namba ya gari/chassis, serial, ownership, eneo..." /></label>
   <div className="mt-4 grid gap-4 md:grid-cols-2"><label className="rounded-2xl border p-4 text-sm font-bold">📷 Picha za dhamana<input type="file" accept="image/*" capture="environment" multiple onChange={addPhotos} className="mt-2 block w-full rounded-xl border p-3"/></label><label className="rounded-2xl border p-4 text-sm font-bold">📎 Nyaraka / documents<input type="file" accept="image/*,.pdf,.doc,.docx" multiple onChange={addDocs} className="mt-2 block w-full rounded-xl border p-3"/></label></div>
   {photos.length>0&&<div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-5">{photos.map((p,i)=><div key={i} className="overflow-hidden rounded-xl border"><img src={p} className="h-28 w-full object-cover" alt={'Collateral '+i}/><button type="button" onClick={()=>setPhotos(x=>x.filter((_,j)=>j!==i))} className="w-full py-1 text-xs font-bold text-red-600">Ondoa</button></div>)}</div>}
   {documents.length>0&&<div className="mt-4 space-y-2">{documents.map((d,i)=><div key={i} className="flex justify-between rounded-xl border p-3 text-sm"><span className="truncate">{d.name}</span><button type="button" onClick={()=>setDocuments(x=>x.filter((_,j)=>j!==i))} className="text-red-600">Ondoa</button></div>)}</div>}
   <button disabled={busy||!description.trim()} onClick={save} className="mt-5 w-full rounded-xl bg-blue-600 px-4 py-3 font-black text-white disabled:opacity-50">{busy?'Inahifadhi...':'Hifadhi Dhamana + Picha + Nyaraka'}</button>
  </section>
  <section className="rounded-3xl border bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h2 className="text-xl font-black">Evidence zilizohifadhiwa</h2><p className="text-sm text-slate-500">Zote zimeunganishwa na Loan ID.</p><div className="mt-4 space-y-3">{records.length===0?<div className="rounded-xl bg-slate-50 p-5 text-sm text-slate-500">Hakuna evidence bado.</div>:records.map((r:any)=><div key={r.id} className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border p-4"><div><b>{r.type}</b><div className="text-sm text-slate-500">{r.description} · {money(r.value)}</div><div className="text-xs text-slate-500">{r.verificationStatus} · {r.documentReference||'Hakuna docs'}</div></div><button onClick={()=>view(r.id)} className="rounded-xl border px-3 py-2 text-xs font-black">👁 Angalia / Download</button></div>)}</div></section>
  {viewing&&<div className="fixed inset-0 z-50 overflow-y-auto bg-black/70 p-4" onClick={()=>setViewing(null)}><div className="mx-auto max-w-5xl rounded-3xl bg-white p-6 dark:bg-slate-900" onClick={e=>e.stopPropagation()}><div className="flex justify-between"><h2 className="text-xl font-black">Evidence</h2><button onClick={()=>setViewing(null)} className="rounded-xl border px-3 py-2">Funga</button></div><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{(viewing.photos||[]).map((p:string,i:number)=><img key={i} src={p} alt={'Evidence '+i} className="h-48 w-full rounded-xl border object-cover"/>)}</div><div className="mt-5 space-y-2">{(viewing.documents||[]).map((d:any,i:number)=><a key={i} href={d.data} download={d.name||'document'} target="_blank" rel="noreferrer" className="block rounded-xl border p-3 font-bold text-blue-700">{d.name||'Document'} · Fungua / Download</a>)}</div></div></div>}
 </div></main>;
}