'use client';

import {useEffect,useMemo,useState} from 'react';
import {useRouter} from 'next/navigation';
import {Download,Eye,RefreshCw,ShieldCheck,UserCheck} from 'lucide-react';
import api,{agreementAPI,loanProductAPI} from '@/lib/api';

const money=(v:any)=>new Intl.NumberFormat('sw-TZ',{style:'currency',currency:'TZS',maximumFractionDigits:0}).format(Number(v||0));
const statusText:any={SUBMITTED:'Jipya — lender aanze review',UNDER_REVIEW:'Review / offer',CONVERTED:'Loan imetengenezwa',REJECTED:'Limekataliwa',CANCELLED:'Limefungwa'};

export default function GeneralApplicationsPage(){
 const router=useRouter();const [apps,setApps]=useState<any[]>([]),[products,setProducts]=useState<any[]>([]),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false);
 const load=async()=>{setMsg('');try{const [a,p]=await Promise.all([api.get('/general-loan-applications/pending'),loanProductAPI.active()]);setApps(a.data?.data??[]);setProducts(p.data?.data??[])}catch(e:any){setMsg(e?.response?.data?.message||'Imeshindikana kupakia maombi')}};useEffect(()=>{load()},[]);
 const act=async(fn:any,ok='Action imekamilika')=>{setBusy(true);setMsg('');try{await fn();setMsg(ok);await load()}catch(e:any){setMsg(e?.response?.data?.message||'Action imeshindikana')}finally{setBusy(false)}};
 const openPdf=async(id:number,download=false)=>{try{const r=await agreementAPI.applicationPreview(id);const url=URL.createObjectURL(r.data);if(download){const a=document.createElement('a');a.href=url;a.download='loan-application-'+id+'-offer.pdf';a.click()}else window.open(url,'_blank','noopener,noreferrer');setTimeout(()=>URL.revokeObjectURL(url),10000)}catch(e:any){setMsg(e?.response?.data?.message||'PDF haipatikani')}};
 const grouped=useMemo(()=>({new:apps.filter(a=>a.status==='SUBMITTED'),review:apps.filter(a=>a.status==='UNDER_REVIEW')}),[apps]);

 return <main className="min-h-screen bg-slate-50 p-4 dark:bg-slate-950 sm:p-6"><div className="mx-auto max-w-7xl space-y-5">
  <section className="rounded-3xl bg-gradient-to-br from-indigo-700 to-slate-950 p-6 text-white shadow-xl"><div className="flex flex-wrap items-start justify-between gap-3"><div><button onClick={()=>router.push('/lender')} className="mb-4 rounded-xl border border-white/30 px-3 py-2 text-xs font-bold">← Rudi Lender Dashboard</button><h1 className="text-3xl font-black">Loan Application Queue</h1><p className="mt-2 max-w-3xl text-sm text-indigo-100">Hapa lender anaona nani ameomba, kiasi gani, status gani na action gani inayofuata. Hakuna application inayopotea kwenye maelekezo.</p></div><button onClick={load} className="rounded-xl bg-white/10 px-4 py-2 text-sm font-bold"><RefreshCw className="mr-1 inline h-4 w-4"/>Refresh</button></div></section>
  <div className="grid gap-3 sm:grid-cols-3"><div className="rounded-2xl border bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><div className="text-xs text-slate-500">New requests</div><div className="mt-2 text-3xl font-black">{grouped.new.length}</div></div><div className="rounded-2xl border bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><div className="text-xs text-slate-500">Under review / offer</div><div className="mt-2 text-3xl font-black">{grouped.review.length}</div></div><div className="rounded-2xl border bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><div className="text-xs text-slate-500">Queue total</div><div className="mt-2 text-3xl font-black">{apps.length}</div></div></div>
  {msg&&<div className="rounded-2xl border border-blue-200 bg-blue-50 p-4 text-sm font-semibold text-blue-800">{msg}</div>}
  {apps.length===0&&<div className="rounded-3xl border bg-white p-10 text-center text-sm text-slate-500 dark:border-slate-800 dark:bg-slate-900">Hakuna application inayosubiri action.</div>}
  <div className="space-y-4">{apps.map(a=><article key={a.id} className="rounded-3xl border bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900">
   <div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><b className="text-xl">Application #{a.id}</b><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-black dark:bg-slate-800">{statusText[a.status]||a.status}</span></div><p className="mt-1 text-sm text-slate-500"><b>{a.borrower?.fullName||'Mkopaji hajulikani'}</b> · {a.borrower?.phone||'—'} · {a.borrower?.email||'—'}</p></div><div className="rounded-xl bg-blue-50 p-3 text-blue-700"><UserCheck className="h-5 w-5"/></div></div>
   <div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div className="rounded-xl bg-slate-50 p-3 dark:bg-slate-950"><span className="text-xs text-slate-500">Ameomba</span><b className="block">{money(a.amount)}</b></div><div className="rounded-xl bg-slate-50 p-3 dark:bg-slate-950"><span className="text-xs text-slate-500">Muda</span><b className="block">{a.duration} {a.durationUnit||'DAYS'}</b></div><div className="rounded-xl bg-slate-50 p-3 dark:bg-slate-950"><span className="text-xs text-slate-500">Gharama + madeni</span><b className="block">{money(Number(a.monthlyExpenses||0)+Number(a.existingMonthlyDebt||0))}/mwezi</b></div><div className="rounded-xl bg-slate-50 p-3 dark:bg-slate-950"><span className="text-xs text-slate-500">Dhamana</span><b className="block">{a.collateralDescription||'Hakuna'}</b></div></div>
   <div className="mt-3 rounded-2xl border p-4 dark:border-slate-800"><div className="text-xs font-black uppercase text-slate-500">Purpose</div><div className="mt-1 font-semibold">{a.purpose||'—'}</div><div className="mt-2 text-xs text-slate-500">Collateral value: {money(a.collateralValue)} · Product: {a.product?.name||'Haijawekwa'}</div></div>
   <div className="mt-4 flex flex-wrap gap-2">
    {a.status==='SUBMITTED'&&<button disabled={busy} onClick={()=>act(()=>api.put('/general-loan-applications/'+a.id+'/review'),'Application imehamia UNDER_REVIEW.')} className="rounded-xl bg-blue-600 px-4 py-2 text-sm font-black text-white">Anza review</button>}
    {a.status==='UNDER_REVIEW'&&<select disabled={busy} defaultValue={a.product?.id||''} onChange={e=>e.target.value&&act(()=>api.put('/general-loan-applications/'+a.id+'/assign-product/'+e.target.value),'Offer imeandaliwa; borrower ataona kwenye Offer page.')} className="rounded-xl border px-3 py-2 text-sm dark:border-slate-700 dark:bg-slate-950"><option value="">Chagua product / tengeneza offer</option>{products.map(p=><option key={p.id} value={p.id}>{p.name} · {p.interestRate}% · {p.durationUnit}</option>)}</select>}
    {a.product&&<><button onClick={()=>openPdf(a.id,false)} className="rounded-xl border px-4 py-2 text-sm font-black"><Eye className="mr-1 inline h-4 w-4"/>Soma Offer</button><button onClick={()=>openPdf(a.id,true)} className="rounded-xl border px-4 py-2 text-sm font-black"><Download className="mr-1 inline h-4 w-4"/>Download</button></>}
    {a.product&&a.termsAccepted&&<button disabled={busy} onClick={()=>act(()=>api.put('/general-loan-applications/'+a.id+'/approve'),'Offer imekubaliwa na loan imetengenezwa. Sasa nenda kwenye loan/signature workflow.')} className="rounded-xl bg-emerald-600 px-4 py-2 text-sm font-black text-white">✓ Approve & Create Loan</button>}
    {a.product&&!a.termsAccepted&&<span className="rounded-xl bg-amber-50 px-4 py-2 text-sm font-bold text-amber-700"><ShieldCheck className="mr-1 inline h-4 w-4"/>Subiri borrower akubali offer</span>}
    <button onClick={()=>router.push('/admin/credit-assessments?applicationId='+a.id)} className="rounded-xl border px-4 py-2 text-sm font-bold">Credit assessment</button>
   </div>
  </article>)}</div>
  <button onClick={()=>router.push('/lender')} className="font-bold text-blue-600">← Rudi Lender Dashboard</button>
 </div></main>
