'use client';

import {useEffect,useRef,useState} from 'react';
import {useRouter} from 'next/navigation';
import Link from 'next/link';
import {Camera,CheckCircle2,RefreshCw,ShieldCheck} from 'lucide-react';
import api,{loanAPI} from '@/lib/api';

const money=(v:any)=>new Intl.NumberFormat('sw-TZ',{style:'currency',currency:'TZS',maximumFractionDigits:0}).format(Number(v||0));

export default function OnsiteGuarantorPage(){
 const router=useRouter();const canvasRef=useRef<HTMLCanvasElement|null>(null);const [loan,setLoan]=useState<any>(null),[loanId,setLoanId]=useState(''),[name,setName]=useState(''),[phone,setPhone]=useState(''),[idNumber,setIdNumber]=useState(''),[relationship,setRelationship]=useState(''),[amount,setAmount]=useState(''),[photo,setPhoto]=useState(''),[busy,setBusy]=useState(false),[msg,setMsg]=useState(''),[drawing,setDrawing]=useState(false);

 useEffect(()=>{const q=new URLSearchParams(window.location.search).get('loanId')||'';setLoanId(q);if(q)loanAPI.get(Number(q)).then(r=>setLoan(r.data?.data??r.data)).catch(e=>setMsg(e?.response?.data?.message||'Loan haipatikani'))},[]);
 const pos=(e:any)=>{const c=canvasRef.current;if(!c)return{x:0,y:0};const r=c.getBoundingClientRect();return{x:(e.clientX-r.left)*(c.width/r.width),y:(e.clientY-r.top)*(c.height/r.height)}};
 const start=(e:any)=>{const c=canvasRef.current;if(!c)return;setDrawing(true);const p=pos(e);const ctx=c.getContext('2d')!;ctx.beginPath();ctx.moveTo(p.x,p.y)};
 const move=(e:any)=>{const c=canvasRef.current;if(!c||!drawing)return;const p=pos(e);const ctx=c.getContext('2d')!;ctx.lineWidth=3;ctx.lineCap='round';ctx.lineTo(p.x,p.y);ctx.stroke()};
 const clear=()=>{const c=canvasRef.current;if(c)c.getContext('2d')!.clearRect(0,0,c.width,c.height)};
 const capturePhoto=(file?:File)=>{if(!file)return;const reader=new FileReader();reader.onload=()=>setPhoto(String(reader.result));reader.readAsDataURL(file)};
 const submit=async(e:any)=>{e.preventDefault();const c=canvasRef.current;if(!loanId||!loan||!photo||!c||!name.trim()||Number(amount)<=0)return setMsg('Jaza taarifa, piga picha na mdhamini asaini kwanza.');const signatureData=c.toDataURL('image/png');setBusy(true);setMsg('');try{await api.post('/guarantors/loan/'+loanId+'/onsite',{name,phone,idNumber,relationship,guaranteedAmount:Number(amount),photoData:photo,signatureData});setMsg('Mdhamini wa onsite amerekodiwa, picha na sahihi zimehifadhiwa kwenye workflow ya agreement.');clear();setTimeout(()=>router.push('/lender'),1200)}catch(e:any){setMsg(e?.response?.data?.message||'Imeshindikana kuhifadhi mdhamini')}finally{setBusy(false)}};

 return <main className="min-h-screen bg-slate-50 p-4 dark:bg-slate-950 sm:p-6"><div className="mx-auto max-w-4xl space-y-5">
  <section className="rounded-3xl bg-gradient-to-br from-indigo-700 to-slate-950 p-6 text-white"><button onClick={()=>router.push('/lender')} className="mb-4 rounded-xl border border-white/30 px-3 py-2 text-xs font-bold">← Rudi Lender</button><h1 className="text-3xl font-black">Mdhamini yupo hapa</h1><p className="mt-2 text-sm text-indigo-100">Lender anaweza kumpiga picha mdhamini, kumueleza mkopo anaoudhamini, na mdhamini asaini kwenye kifaa hiki bila kuwa na account.</p></section>
  {msg&&<div className="rounded-2xl border bg-white p-4 text-sm font-semibold dark:bg-slate-900">{msg}</div>}
  {!loan?<div className="rounded-3xl border bg-white p-8 text-center dark:border-slate-800 dark:bg-slate-900"><p className="text-sm text-slate-500">Loan haijapatikana. Fungua page hii kutoka kwenye loan yenyewe.</p></div>:
  <form onSubmit={submit} className="space-y-5 rounded-3xl border bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900">
   <div className="grid gap-3 sm:grid-cols-3"><div className="rounded-2xl bg-blue-50 p-4 dark:bg-blue-950/30"><div className="text-xs text-slate-500">Mkopaji</div><b>{loan.borrower?.fullName||'—'}</b></div><div className="rounded-2xl bg-blue-50 p-4 dark:bg-blue-950/30"><div className="text-xs text-slate-500">Loan</div><b>#{loan.id}</b></div><div className="rounded-2xl bg-blue-50 p-4 dark:bg-blue-950/30"><div className="text-xs text-slate-500">Kiasi cha mkopo</div><b>{money(loan.amount)}</b></div></div>
   <div className="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><ShieldCheck className="mr-2 inline h-5 w-5"/>Mdhamini anatakiwa kuthibitisha kwamba anaelewa <b>mkopaji huyu</b>, kiasi cha mkopo <b>{money(loan.amount)}</b>, na liability inayowekwa hapa <b>{money(Number(amount||0))}</b>.</div>
   <div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold">Jina kamili<input required value={name} onChange={e=>setName(e.target.value)} className="mt-1 w-full rounded-xl border p-3 dark:border-slate-700 dark:bg-slate-950"/></label><label className="text-sm font-bold">Simu (hiari)<input value={phone} onChange={e=>setPhone(e.target.value)} className="mt-1 w-full rounded-xl border p-3 dark:border-slate-700 dark:bg-slate-950"/></label><label className="text-sm font-bold">Namba ya kitambulisho (hiari)<input value={idNumber} onChange={e=>setIdNumber(e.target.value)} className="mt-1 w-full rounded-xl border p-3 dark:border-slate-700 dark:bg-slate-950"/></label><label className="text-sm font-bold">Uhusiano<input value={relationship} onChange={e=>setRelationship(e.target.value)} placeholder="Mfano: ndugu / rafiki" className="mt-1 w-full rounded-xl border p-3 dark:border-slate-700 dark:bg-slate-950"/></label><label className="text-sm font-bold sm:col-span-2">Kiasi anachodhamini (TZS)<input required min="0" max={loan.amount} type="number" value={amount} onChange={e=>setAmount(e.target.value)} className="mt-1 w-full rounded-xl border p-3 dark:border-slate-700 dark:bg-slate-950"/></label></div>
   <div className="grid gap-5 md:grid-cols-2"><div className="rounded-2xl border p-4 dark:border-slate-800"><h2 className="font-black"><Camera className="mr-2 inline h-5 w-5 text-blue-600"/>Picha ya mdhamini</h2><label className="mt-3 inline-flex cursor-pointer items-center gap-2 rounded-xl bg-blue-600 px-4 py-3 text-sm font-black text-white">Piga picha<input required type="file" accept="image/*" capture="user" className="hidden" onChange={e=>capturePhoto(e.target.files?.[0])}/></label>{photo&&<img src={photo} alt="Mdhamini" className="mt-3 max-h-56 w-full rounded-xl object-cover"/>}</div>
    <div className="rounded-2xl border p-4 dark:border-slate-800"><h2 className="font-black">Sahihi ya mdhamini</h2><canvas ref={canvasRef} width={800} height={260} onPointerDown={start} onPointerMove={move} onPointerUp={()=>setDrawing(false)} onPointerLeave={()=>setDrawing(false)} className="mt-3 h-52 w-full touch-none rounded-xl border-2 border-dashed bg-white"/><button type="button" onClick={clear} className="mt-2 rounded-xl border px-3 py-2 text-xs font-bold">Futa sahihi</button></div></div>
   <label className="flex items-start gap-3 rounded-2xl border bg-slate-50 p-4 text-sm dark:border-slate-800 dark:bg-slate-950"><input required type="checkbox" className="mt-1 h-5 w-5"/><span>Nimesomewa na nimeelewa kwamba namdhamini <b>{loan.borrower?.fullName||'mkopaji'}</b> kwa loan #{loan.id} ya <b>{money(loan.amount)}</b>, na nakubali liability ya <b>{money(Number(amount||0))}</b> iliyoandikwa hapa.</span></label>
   <button disabled={busy} className="w-full rounded-xl bg-emerald-600 px-5 py-3 font-black text-white disabled:opacity-50">{busy?<><RefreshCw className="mr-2 inline h-4 w-4 animate-spin"/>Inahifadhi...</>:<><CheckCircle2 className="mr-2 inline h-4 w-4"/>Hifadhi mdhamini, picha na sahihi</>}</button>
  </form>}
  <Link href="/lender" className="font-bold text-blue-600">← Rudi Lender Dashboard</Link>
 </div></main>
}
