'use client';

import {useEffect,useState} from 'react';
import {useRouter} from 'next/navigation';
import api from '@/lib/api';

const money=(v:any)=>new Intl.NumberFormat('sw-TZ',{style:'currency',currency:'TZS',maximumFractionDigits:0}).format(Number(v||0));
export default function LoanOfferPage(){
 const router=useRouter();const [apps,setApps]=useState<any[]>([]);const [msg,setMsg]=useState('');
 useEffect(()=>{(async()=>{try{const r=await api.get('/general-loan-applications/mine');setApps(r.data?.data??r.data??[])}catch(e:any){setMsg(e?.response?.data?.message||'Imeshindikana kupakia offer')}})()},[]);
 const accept=async(id:number)=>{try{await api.put('/general-loan-applications/'+id+'/accept-offer');setMsg('Offer imekubaliwa.');const r=await api.get('/general-loan-applications/mine');setApps(r.data?.data??r.data??[])}catch(e:any){setMsg(e?.response?.data?.message||'Imeshindikana')}}
 return <main className="min-h-screen bg-slate-50 p-6 dark:bg-slate-950"><div className="mx-auto max-w-4xl space-y-6"><section className="rounded-3xl bg-white p-6 shadow-sm dark:bg-slate-900"><h1 className="text-2xl font-black">Loan Offers & Agreements</h1><p className="mt-2 text-sm text-slate-500">Soma offer, fungua PDF ya mkataba, pakua, kisha kubali masharti kabla ya approval.</p></section>{msg&&<div className="rounded-2xl bg-white p-4 text-sm dark:bg-slate-900">{msg}</div>}{apps.map(a=><div key={a.id} className="rounded-3xl border bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="flex flex-wrap justify-between gap-2"><b>Application #{a.id}</b><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold">{a.status}</span></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><div>Kiasi: <b>{money(a.amount)}</b></div><div>Muda: <b>{a.duration} {a.durationUnit||'DAYS'}</b></div><div>Product: <b>{a.product?.name||'Inasubiri lender'}</b></div><div>Jumla: <b>{money(a.totalRepaymentSnapshot)}</b></div><div>Riba: <b>{money(a.interestSnapshot)}</b></div><div>Ada: <b>{money(a.processingFeeSnapshot)}</b></div></div>{a.product&&a.status==='UNDER_REVIEW'&&<div className="mt-5 flex flex-wrap gap-2"><a target="_blank" rel="noreferrer" href={(process.env.NEXT_PUBLIC_API_URL||'')+'/api/agreements/application/'+a.id+'/preview'} className="rounded-xl border px-4 py-2 text-sm font-bold">Soma Agreement</a><a href={(process.env.NEXT_PUBLIC_API_URL||'')+'/api/agreements/application/'+a.id+'/pdf'} className="rounded-xl border px-4 py-2 text-sm font-bold">Download PDF</a><button onClick={()=>accept(a.id)} className="rounded-xl bg-blue-600 px-4 py-2 text-sm font-bold text-white">Nimesoma & Nakubali</button></div>}</div>)}<button onClick={()=>router.push('/borrower')} className="font-bold text-blue-600">Rudi Dashboard</button></div></main>
}
