'use client';

import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {Calculator,Download,FileText,LogOut,RefreshCw,WalletCards,CheckCircle2,Clock3,AlertTriangle} from 'lucide-react';
import {bursarAPI,paymentAPI} from '@/lib/api';
import LanguageSwitcher from '@/components/LanguageSwitcher';

const money=(v:any)=>new Intl.NumberFormat('sw-TZ',{style:'currency',currency:'TZS',maximumFractionDigits:0}).format(Number(v||0));
const unwrap=(r:any)=>r?.data?.data??r?.data??[];
export default function BursarPage(){
 const router=useRouter();const [user,setUser]=useState<any>(null),[summary,setSummary]=useState<any>({}),[loans,setLoans]=useState<any[]>([]),[payments,setPayments]=useState<any[]>([]),[search,setSearch]=useState(''),[busy,setBusy]=useState(false),[msg,setMsg]=useState('');
 const load=async()=>{try{const [s,l,p]=await Promise.all([bursarAPI.summary(),bursarAPI.loans(),bursarAPI.payments()]);setSummary(unwrap(s));setLoans(unwrap(l));setPayments(unwrap(p));}catch(e:any){setMsg(e?.response?.data?.message||'Imeshindikana kupakia finance workspace.')}}
 useEffect(()=>{const t=localStorage.getItem('token'),raw=localStorage.getItem('user');if(!t||!raw){router.push('/login');return}const u=JSON.parse(raw);if(u.role!=='BURSER'){router.push('/dashboard');return}setUser(u);load();},[router]);
 const confirm=async(p:any)=>{setBusy(true);try{await paymentAPI.confirm(p.id,p.transactionId||'');setMsg('Malipo yamethibitishwa.');await load();}catch(e:any){setMsg(e?.response?.data?.message||'Imeshindikana kuthibitisha malipo.')}finally{setBusy(false)}};
 const filtered=useMemo(()=>loans.filter(l=>`${l.id} ${l.borrower||''} ${l.borrowerEmail||''} ${l.status||''}`.toLowerCase().includes(search.toLowerCase())),[loans,search]);
 const download=async()=>{try{const r=await bursarAPI.report();const u=URL.createObjectURL(r.data);const a=document.createElement('a');a.href=u;a.download='bursar-loan-report.csv';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}catch(e:any){setMsg(e?.response?.data?.message||'Report haikupatikana.')}}
 const logout=()=>{localStorage.clear();document.cookie='token=; path=/; max-age=0';router.push('/login')};
 if(!user)return null;
 return <div className="min-h-screen bg-slate-50 text-slate-900 dark:bg-slate-950 dark:text-white"><nav className="sticky top-0 z-40 border-b bg-white/95 px-4 py-3 dark:border-slate-800 dark:bg-slate-900/95"><div className="mx-auto flex max-w-7xl items-center justify-between"><Link href="/" className="font-black">💰 JmkLoanApp · Burser</Link><div className="flex items-center gap-2"><LanguageSwitcher/><button onClick={logout} className="rounded-xl px-3 py-2 text-sm font-semibold text-red-600"><LogOut className="mr-1 inline h-4 w-4"/>Toka</button></div></div></nav>
 <main className="mx-auto max-w-7xl space-y-6 p-4 sm:p-6"><section className="rounded-3xl bg-gradient-to-br from-emerald-700 via-teal-700 to-slate-950 p-7 text-white shadow-xl"><p className="text-sm text-emerald-100">Finance & Loan Operations</p><h1 className="text-3xl font-black">Burser Workspace</h1><p className="mt-2 max-w-3xl text-sm text-emerald-100">Simamia fedha, malipo, portfolio ya mikopo, reconciliation na taarifa za kifedha bila kupewa mamlaka ya kuidhinisha mkopo.</p></section>
 {msg&&<div className="rounded-2xl border border-blue-200 bg-blue-50 p-4 text-sm text-blue-800">{msg}</div>}
 <div className="flex flex-wrap gap-2"><button onClick={load} className="rounded-xl border bg-white px-4 py-2 text-sm font-black dark:border-slate-800 dark:bg-slate-900"><RefreshCw className="mr-1 inline h-4 w-4"/>Refresh</button><button onClick={download} className="rounded-xl bg-emerald-600 px-4 py-2 text-sm font-black text-white"><Download className="mr-1 inline h-4 w-4"/>Export Loan Report</button><Link href="/repayments" className="rounded-xl border bg-white px-4 py-2 text-sm font-black dark:border-slate-800 dark:bg-slate-900">Repayments</Link></div>
 <section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[['Portfolio',summary.disbursedValue,WalletCards],['Receivable',summary.portfolioReceivable,FileText],['Payments received',summary.paymentsReceived,CheckCircle2],['Pending payments',summary.pendingPayments,Clock3]].map(([a,v,I]:any)=><div key={a} className="rounded-2xl border bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><I className="h-5 w-5 text-emerald-600"/><div className="mt-2 text-2xl font-black">{money(v)}</div><div className="text-sm text-slate-500">{a}</div></div>)}</section>
 <section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{[['Loans',summary.loanCount,FileText],['Pending',summary.pendingLoans,Clock3],['Active',summary.activeLoans,WalletCards],['Paid',summary.paidLoans,CheckCircle2],['Defaulted',summary.defaultedLoans,AlertTriangle]].map(([a,v,I]:any)=><div key={a} className="rounded-2xl border bg-white p-4 dark:border-slate-800 dark:bg-slate-900"><I className="h-4 w-4 text-emerald-600"/><div className="mt-2 text-xl font-black">{v||0}</div><div className="text-xs text-slate-500">{a}</div></div>)}</section>
 <section className="rounded-3xl border border-emerald-200 bg-white p-6 shadow-sm dark:border-emerald-900 dark:bg-slate-900"><div className="flex items-center gap-3"><Calculator className="h-6 w-6 text-emerald-600"/><div><h2 className="text-xl font-black">Financial Calculator</h2><p className="text-sm text-slate-500">Kokotoa simple interest, total repayment na installment kwa analysis ya fedha.</p></div></div><CalculatorBox/></section>
 <section className="rounded-3xl border bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="flex flex-wrap items-center justify-between gap-3 border-b p-5 dark:border-slate-800"><div><h2 className="text-xl font-black">Loan Portfolio</h2><p className="text-sm text-slate-500">Taarifa za fedha na status za mikopo.</p></div><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Tafuta borrower / loan..." className="rounded-xl border p-2.5 text-sm dark:border-slate-700 dark:bg-slate-950"/></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b dark:border-slate-800"><th className="p-4">Loan</th><th className="p-4">Borrower</th><th className="p-4">Amount</th><th className="p-4">Receivable</th><th className="p-4">Status</th><th className="p-4">Next due</th></tr></thead><tbody>{filtered.map(l=><tr key={l.id} className="border-b last:border-0 dark:border-slate-800"><td className="p-4 font-bold">#{l.id}</td><td className="p-4">{l.borrower}<div className="text-xs text-slate-500">{l.borrowerEmail}</div></td><td className="p-4">{money(l.amount)}</td><td className="p-4">{money(l.totalRepayment)}</td><td className="p-4"><span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-bold dark:bg-slate-800">{l.status}</span></td><td className="p-4">{l.nextDueDate||'—'}</td></tr>)}</tbody></table>{filtered.length===0&&<div className="p-8 text-center text-sm text-slate-500">Hakuna records.</div>}</div></section>
 <section className="rounded-3xl border bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="border-b p-5 dark:border-slate-800"><h2 className="text-xl font-black">Payment Reconciliation</h2><p className="text-sm text-slate-500">Thibitisha malipo yenye transaction reference; action hii haiidhinishi loan.</p></div><div className="divide-y dark:divide-slate-800">{payments.map(p=><div key={p.id} className="flex flex-col gap-3 p-5 sm:flex-row sm:items-center sm:justify-between"><div><b>{money(p.amount)} · Loan #{p.loanId}</b><p className="text-xs text-slate-500">{p.borrower} · {p.method} · {p.transactionId||'No reference'} · {p.status}</p></div>{p.status==='PENDING'&&<button disabled={busy} onClick={()=>confirm(p)} className="rounded-xl bg-emerald-600 px-4 py-2 text-xs font-black text-white disabled:opacity-50">Thibitisha</button>}</div>)}</div></section>
 </main></div>;
}
function CalculatorBox(){const [a,setA]=useState(''),[r,setR]=useState(''),[m,setM]=useState(''),[f,setF]=useState('');const p=Number(a),rate=Number(r),months=Number(m),fee=Number(f||0);const interest=p*rate/100*(months/12),total=p+interest+fee,install=months?total/months:0;return <div className="mt-5 grid gap-3 sm:grid-cols-4"><input type="number" min="1" placeholder="Principal" value={a} onChange={e=>setA(e.target.value)} className="rounded-xl border p-3 dark:border-slate-700 dark:bg-slate-950"/><input type="number" min="0" step="0.01" placeholder="Annual rate %" value={r} onChange={e=>setR(e.target.value)} className="rounded-xl border p-3 dark:border-slate-700 dark:bg-slate-950"/><input type="number" min="1" placeholder="Months" value={m} onChange={e=>setM(e.target.value)} className="rounded-xl border p-3 dark:border-slate-700 dark:bg-slate-950"/><input type="number" min="0" placeholder="Fee" value={f} onChange={e=>setF(e.target.value)} className="rounded-xl border p-3 dark:border-slate-700 dark:bg-slate-950"/><div className="sm:col-span-4 grid gap-3 sm:grid-cols-3">{[['Interest',interest],['Total repayment',total],['Installment',install]].map(([x,v]:any)=><div key={x} className="rounded-xl bg-slate-50 p-4 dark:bg-slate-950"><span className="text-xs text-slate-500">{x}</span><div className="font-black">{money(v)}</div></div>)}</div></div>}
