'use client';

import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { CheckCircle2, Clock3, CreditCard, FileText, LogOut, RefreshCw, ShieldCheck, WalletCards } from 'lucide-react';
import { loanAPI, loanApplicationAPI, loanProductAPI, guarantorAPI, loanQuoteAPI, preAgreementAPI } from '@/lib/api';
import LanguageSwitcher from '@/components/LanguageSwitcher';
import { useLanguage } from '@/lib/useLanguage';

const money=(v:any)=>new Intl.NumberFormat('sw-TZ',{style:'currency',currency:'TZS',maximumFractionDigits:0}).format(Number(v||0));
const unwrap=(r:any)=>r?.data?.data??r?.data??[];
const labels:any={sw:{title:'Dashboard ya Mkopaji',welcome:'Karibu',subtitle:'Dhibiti maombi, mikopo, marejesho na nyaraka zako.',loans:'Mikopo yangu',total:'Jumla ya mikopo',active:'Mikopo inayoendelea',paid:'Imelipwa',pending:'Inasubiri',amount:'Kiasi',status:'Hali',actions:'Vitendo',pay:'Lipa',schedule:'Ratiba',agreement:'Mkataba PDF',profile:'Wasifu',logout:'Toka',empty:'Huna mikopo bado.',refresh:'Onyesha upya'},en:{title:'Borrower Dashboard',welcome:'Welcome',subtitle:'Manage your applications, loans, repayments and documents.',loans:'My loans',total:'Total loans',active:'Active loans',paid:'Paid',pending:'Pending',amount:'Amount',status:'Status',actions:'Actions',pay:'Pay',schedule:'Schedule',agreement:'PDF agreement',profile:'Profile',logout:'Logout',empty:'You have no loans yet.',refresh:'Refresh'}};

export default function BorrowerPage(){
 const router=useRouter(); const {lang}=useLanguage(); const t=labels[lang];
 const [products,setProducts]=useState<any[]>([]),[calcProductId,setCalcProductId]=useState(''),[calcAmount,setCalcAmount]=useState(''),[calcDuration,setCalcDuration]=useState(''),[applications,setApplications]=useState<any[]>([]),[productId,setProductId]=useState(''),[amount,setAmount]=useState(''),[duration,setDuration]=useState(''),[purpose,setPurpose]=useState(''),[submitting,setSubmitting]=useState(false),[quote,setQuote]=useState<any>(null),[quoteBusy,setQuoteBusy]=useState(false),[termsAccepted,setTermsAccepted]=useState(false);
 const [user,setUser]=useState<any>(null),[guarantees,setGuarantees]=useState<any[]>([]),[loans,setLoans]=useState<any[]>([]),[loading,setLoading]=useState(true),[err,setErr]=useState('');
 useEffect(()=>{const token=localStorage.getItem('token'),raw=localStorage.getItem('user');if(!token||!raw){router.push('/login');return}const u=JSON.parse(raw);if(u.role!=='BORROWER'){router.push('/dashboard');return}setUser(u);load();},[router]);
 const load=async()=>{setLoading(true);try{const [r,a,p,g]=await Promise.all([loanAPI.byBorrower(),loanApplicationAPI.mine(),loanProductAPI.active(),guarantorAPI.mine()]);setApplications(Array.isArray(unwrap(a))?unwrap(a):[]);setProducts(Array.isArray(unwrap(p))?unwrap(p):[]);setLoans(Array.isArray(unwrap(r))?unwrap(r):[]);setGuarantees(Array.isArray(unwrap(g))?unwrap(g):[]);setErr('')}catch(e:any){setErr(e?.response?.data?.message||'Failed to load loans')}finally{setLoading(false)}};
 const buildQuote=async()=>{if(!productId||!amount||!duration)return;setQuoteBusy(true);setErr('');try{const r=await loanQuoteAPI.quote({productId:Number(productId),amount:Number(amount),duration:Number(duration)});setQuote(r.data?.data??r.data);setTermsAccepted(false);}catch(e:any){setQuote(null);setErr(e?.response?.data?.message||'Imeshindikana kupata masharti ya mkopo.');}finally{setQuoteBusy(false)}};
 const downloadPreAgreement=async()=>{if(!quote)return;try{const r=await preAgreementAPI.pdf({productId:Number(productId),amount:Number(amount),duration:Number(duration)},purpose||'Loan application');const url=URL.createObjectURL(r.data);const a=document.createElement('a');a.href=url;a.download='pre-loan-offer.pdf';a.click();URL.revokeObjectURL(url);}catch(e:any){setErr(e?.response?.data?.message||'PDF haikupatikana.');}};
 const calculator=useMemo(()=>{const p=products.find(x=>String(x.id)===calcProductId);const principal=Number(calcAmount||0);const months=Number(calcDuration||0);if(!p||principal<=0||months<=0)return null;const rate=Number(p.interestRate||0);const interest=p.interestType==='FLAT'?principal*rate/100:(principal*rate/100)*(months/12);const fee=Number(p.processingFee||0);const total=principal+interest+fee;return {p,interest,fee,total,installment:total/months};},[products,calcProductId,calcAmount,calcDuration]);
 const stats=useMemo(()=>({total:loans.length,active:loans.filter(x=>['APPROVED','DISBURSED'].includes(x.status)).length,paid:loans.filter(x=>x.status==='PAID').length,pending:loans.filter(x=>x.status==='PENDING').length}),[loans]);
 const logout=()=>{localStorage.clear();document.cookie='token=; path=/; max-age=0';router.push('/login')};
 if(!user)return null;
 return <div className="min-h-screen bg-slate-50 dark:bg-slate-950 text-slate-900 dark:text-white">
  <nav className="sticky top-0 z-40 border-b bg-white/95 px-4 py-3 backdrop-blur dark:border-slate-800 dark:bg-slate-900/95"><div className="mx-auto flex max-w-7xl items-center justify-between">
   <Link href="/" className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-blue-600 text-xl text-white">💰</div><div><b>JmkLoanApp</b><div className="text-[10px] text-slate-500">{t.title}</div></div></Link>
   <div className="flex items-center gap-2"><LanguageSwitcher/><Link href="/profile" className="hidden rounded-xl px-3 py-2 text-sm font-semibold hover:bg-slate-100 sm:block">{t.profile}</Link><button onClick={logout} className="flex items-center gap-2 rounded-xl px-3 py-2 text-sm font-semibold text-red-600"><LogOut className="h-4 w-4"/>{t.logout}</button></div>
  </div></nav>
  <main className="mx-auto max-w-7xl space-y-6 p-4 sm:p-6">
   <div className="flex flex-wrap gap-2">
<Link href="/borrower/apply" className="rounded-xl bg-blue-600 px-4 py-2 text-sm font-black text-white">Omba Mkopo</Link>
<Link href="/loan-offer" className="rounded-xl border bg-white px-4 py-2 text-sm font-black dark:bg-slate-900">Offers</Link>
<Link href="/agreements" className="rounded-xl border bg-white px-4 py-2 text-sm font-black dark:bg-slate-900">Agreements</Link>
<Link href="/payments" className="rounded-xl border bg-white px-4 py-2 text-sm font-black dark:bg-slate-900">Lipa</Link>
<Link href="/signatures" className="rounded-xl border bg-white px-4 py-2 text-sm font-black dark:bg-slate-900">Saini</Link>
<Link href="/profile" className="rounded-xl border bg-white px-4 py-2 text-sm font-black dark:bg-slate-900">Wasifu</Link>
</div>
   <section className="rounded-3xl bg-gradient-to-br from-blue-700 to-slate-900 p-6 text-white shadow-xl"><p className="text-sm text-blue-100">{t.welcome}</p><h1 className="text-3xl font-black">{user.fullName}</h1><p className="mt-2 text-sm text-blue-100">{t.subtitle}</p></section>
   <section className="rounded-3xl border border-blue-200 bg-white p-6 shadow-sm dark:border-blue-900 dark:bg-slate-900">
    <div className="flex items-start gap-3"><div className="rounded-xl bg-blue-50 p-3 text-blue-600"><WalletCards className="h-5 w-5"/></div><div><h2 className="text-xl font-black">{lang==='sw'?'Omba Mkopo':'Apply for a loan'}</h2><p className="text-sm text-slate-500">{lang==='sw'?'Chagua bidhaa, kiasi na muda. Ombi litaenda kwa mkopeshaji kwa review.':'Choose a product, amount and duration. Your application goes to a lender for review.'}</p></div></div>
    <form onSubmit={async e=>{e.preventDefault();if(!quote){await buildQuote();return;}if(!termsAccepted)return;setSubmitting(true);setErr('');try{await loanApplicationAPI.submit({productId:Number(productId),amount:Number(amount),duration:Number(duration),purpose,termsAccepted:true});setErr(lang==='sw'?'Ombi limetumwa kwa mkopeshaji.':'Application submitted for lender review.');setAmount('');setDuration('');setPurpose('');setQuote(null);setTermsAccepted(false);await load();}catch(e:any){setErr(e?.response?.data?.message||'Failed');}finally{setSubmitting(false)}}} className="mt-5 grid gap-3 md:grid-cols-4">
      <select required value={productId} onChange={e=>{setProductId(e.target.value);const p=products.find(x=>String(x.id)===e.target.value);setQuote(null);setTermsAccepted(false);if(p){setAmount(p.minAmount);setDuration(p.minDuration)}}} className="rounded-xl border p-3 dark:border-slate-700 dark:bg-slate-950"><option value="">{lang==='sw'?'Chagua bidhaa ya mkopo':'Choose loan product'}</option>{products.map(p=><option key={p.id} value={p.id}>{p.name} · {money(p.minAmount)}–{money(p.maxAmount)}</option>)}</select>
      <input required type="number" min="1" value={amount} onChange={e=>{setAmount(e.target.value);setQuote(null);setTermsAccepted(false)}} placeholder={lang==='sw'?'Kiasi':'Amount'} className="rounded-xl border p-3 dark:border-slate-700 dark:bg-slate-950"/>
      <input required type="number" min="1" value={duration} onChange={e=>{setDuration(e.target.value);setQuote(null);setTermsAccepted(false)}} placeholder={lang==='sw'?'Muda':'Duration'} className="rounded-xl border p-3 dark:border-slate-700 dark:bg-slate-950"/>
      <input required value={purpose} onChange={e=>setPurpose(e.target.value)} placeholder={lang==='sw'?'Madhumuni':'Purpose'} className="rounded-xl border p-3 dark:border-slate-700 dark:bg-slate-950"/>
      <button type="button" disabled={quoteBusy||!productId||!amount||!duration} onClick={buildQuote} className="rounded-xl border border-blue-600 px-4 py-3 font-black text-blue-700 md:col-span-4">{quoteBusy?(lang==='sw'?'Inahesabu...':'Calculating...'):(lang==='sw'?'Onyesha masharti kamili':'Show full loan terms')}</button>
      {quote&&<div className="md:col-span-4 rounded-2xl border border-emerald-200 bg-emerald-50 p-5 dark:border-emerald-900 dark:bg-emerald-950/30">
        <div className="flex flex-wrap items-center justify-between gap-3"><div><b>{quote.productName}</b><p className="text-xs text-slate-500">{quote.interestType} · {quote.repaymentFrequency} · {quote.durationUnit}</p></div><button type="button" onClick={downloadPreAgreement} className="rounded-xl bg-white px-3 py-2 text-sm font-bold shadow-sm dark:bg-slate-900">📄 {lang==='sw'?'Soma / Pakua Agreement':'Read / Download Agreement'}</button></div>
        <div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[
          [lang==='sw'?'Mtaji':'Principal',quote.principal],[lang==='sw'?'Riba':'Interest',quote.interest],[lang==='sw'?'Ada ya usindikaji':'Processing fee',quote.processingFee],[lang==='sw'?'Jumla ya kurejesha':'Total repayment',quote.totalRepayment],
          [lang==='sw'?'Kiasi kwa installment':'Installment amount',quote.installmentAmount],[lang==='sw'?'Idadi ya installments':'Installments',quote.installmentCount],[lang==='sw'?'Late fee':'Late fee',quote.lateFee],[lang==='sw'?'Grace period':'Grace period',quote.gracePeriodDays+' day(s)']
        ].map(([label,value]:any)=><div key={label} className="rounded-xl bg-white p-3 dark:bg-slate-900"><div className="text-xs text-slate-500">{label}</div><div className="font-black">{typeof value==='number'?money(value):value}</div></div>)}</div>
        <div className="mt-4 rounded-xl bg-white p-4 text-sm dark:bg-slate-900"><b>{lang==='sw'?'Ratiba ya malipo':'Repayment dates'}</b><div className="mt-2 grid gap-1 sm:grid-cols-2">{(quote.dueDates||[]).map((d:string,i:number)=><div key={d+i}>#{i+1} — {d} — {money(quote.installmentAmount)}</div>)}</div></div>
        <label className="mt-4 flex items-start gap-2 text-sm font-semibold"><input type="checkbox" checked={termsAccepted} onChange={e=>setTermsAccepted(e.target.checked)} className="mt-1"/><span>{lang==='sw'?'Nimesoma na nimeelewa masharti, riba, ada, jumla ya marejesho, ratiba na masharti ya kuchelewa.':'I have read and understood the interest, fees, total repayment, schedule and late-payment terms.'}</span></label>
        <button type="submit" disabled={submitting||!termsAccepted} className="mt-4 w-full rounded-xl bg-blue-600 px-4 py-3 font-black text-white disabled:opacity-50">{submitting?(lang==='sw'?'Inatuma...':'Submitting...'):(lang==='sw'?'Tuma ombi baada ya kukubali masharti':'Submit application after accepting terms')}</button>
      </div>}
    </form>
   </section>
   <section className="rounded-3xl border border-emerald-200 bg-white p-6 shadow-sm dark:border-emerald-900 dark:bg-slate-900">
    <div className="flex items-start gap-3"><div className="rounded-xl bg-emerald-50 p-3 text-emerald-600">🧮</div><div><h2 className="text-xl font-black">{lang==='sw'?'Calculator ya Mkopo':'Loan Calculator'}</h2><p className="text-sm text-slate-500">{lang==='sw'?'Jua makadirio kabla ya kutuma ombi. Hesabu zinatumia masharti ya loan product.':'Estimate your repayment before applying. Calculations use the selected loan product terms.'}</p></div></div>
    <div className="mt-5 grid gap-3 md:grid-cols-3">
      <select value={calcProductId} onChange={e=>{setCalcProductId(e.target.value);const p=products.find(x=>String(x.id)===e.target.value);if(p){setCalcAmount(p.minAmount);setCalcDuration(p.minDuration)}}} className="rounded-xl border p-3 dark:border-slate-700 dark:bg-slate-950"><option value="">{lang==='sw'?'Chagua bidhaa':'Choose product'}</option>{products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select>
      <input type="number" min="1" value={calcAmount} onChange={e=>setCalcAmount(e.target.value)} placeholder={lang==='sw'?'Kiasi cha mkopo':'Loan amount'} className="rounded-xl border p-3 dark:border-slate-700 dark:bg-slate-950"/>
      <input type="number" min="1" value={calcDuration} onChange={e=>setCalcDuration(e.target.value)} placeholder={lang==='sw'?'Muda kwa miezi':'Months'} className="rounded-xl border p-3 dark:border-slate-700 dark:bg-slate-950"/>
    </div>
    {calculator&&<div className="mt-5 grid gap-3 sm:grid-cols-4">{[[lang==='sw'?'Riba':'Interest',calculator.interest],[lang==='sw'?'Ada':'Fee',calculator.fee],[lang==='sw'?'Jumla ya kurejesha':'Total repayment',calculator.total],[lang==='sw'?'Makadirio kwa mwezi':'Est. monthly',calculator.installment]].map(([label,value]:any)=><div key={label} className="rounded-2xl bg-slate-50 p-4 dark:bg-slate-950"><div className="text-xs text-slate-500">{label}</div><div className="mt-1 text-lg font-black">{money(value)}</div></div>)}</div>}
   </section>
   <section className="rounded-3xl border bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="border-b p-5 dark:border-slate-800"><h2 className="font-black">{lang==='sw'?'Hatua za maombi':'Application journey'}</h2></div><div className="grid gap-3 p-5 md:grid-cols-5">{(lang==='sw'?['Jisajili','Admin anakubali','Omba mkopo','Mkopeshaji anakagua','Mdhamini + approval → mkopo']:['Register','Admin approval','Apply for loan','Lender review','Guarantor + approval → loan']).map((x,i)=><div key={x} className="rounded-2xl border p-4 dark:border-slate-800"><div className="text-xs font-black text-blue-600">STEP {i+1}</div><div className="mt-2 text-sm font-bold">{x}</div></div>)}</div></section>
   <section className="rounded-3xl border bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="border-b p-5 dark:border-slate-800"><h2 className="font-black">{lang==='sw'?'Maombi yangu':'My applications'}</h2></div>{applications.length===0?<div className="p-6 text-sm text-slate-500">{lang==='sw'?'Hujaomba mkopo bado.':'You have not applied for a loan yet.'}</div>:<div className="divide-y dark:divide-slate-800">{applications.map(a=><div key={a.id} className="flex flex-col gap-2 p-5 sm:flex-row sm:items-center sm:justify-between"><div><b>Application #{a.id}</b><p className="text-sm text-slate-500">{a.product?.name} · {money(a.amount)} · {a.durationMonths} months</p></div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold dark:bg-slate-800">{a.status}</span></div>)}</div>}</section>
   <section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[[t.total,stats.total,FileText],[t.active,stats.active,WalletCards],[t.pending,stats.pending,Clock3],[t.paid,stats.paid,CheckCircle2]].map(([x,v,I]:any)=><div className="rounded-2xl border bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900" key={x}><I className="h-5 w-5 text-blue-600"/><div className="mt-3 text-3xl font-black">{v}</div><div className="text-sm text-slate-500">{x}</div></div>)}</section>
   {err&&<div className="rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{err}</div>}
   <section className="rounded-3xl border bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center justify-between border-b p-5 dark:border-slate-800"><div><h2 className="font-black">{t.loans}</h2><p className="text-sm text-slate-500">{user.email}</p></div><button onClick={load} className="rounded-xl border p-2"><RefreshCw className="h-4 w-4"/></button></div>
   {!loading&&loans.length>0&&<section className="rounded-3xl border bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="border-b p-5 dark:border-slate-800"><h2 className="font-black">{lang==='sw'?'Maendeleo ya Mdhamini':'Guarantor progress'}</h2><p className="text-sm text-slate-500">{lang==='sw'?'Hapa utaona hatua ya ombi la mdhamini kwenye kila mkopo.':'Track guarantor requests linked to your loans.'}</p></div><div className="grid gap-3 p-5 md:grid-cols-2">{loans.map(l=>{const gs=guarantees.filter(g=>g.loan?.id===l.id||g.loanId===l.id);const g=gs[0];return <div key={l.id} className="rounded-2xl border p-4 dark:border-slate-800"><div className="flex justify-between"><b>Loan #{l.id}</b><span className="text-xs font-bold">{g?.status||'WAITING'}</span></div><p className="mt-1 text-sm text-slate-500">{g?.guarantor?.fullName|| (lang==='sw'?'Mdhamini bado hajapangiwa':'No guarantor assigned yet')}</p></div>})}</div></section>}
   {loading?<div className="p-10 text-center text-sm text-slate-500">Loading...</div>:loans.length===0?<div className="p-10 text-center text-sm text-slate-500">{t.empty}</div>:<div className="divide-y dark:divide-slate-800">{loans.map(l=><div key={l.id} className="flex flex-col gap-4 p-5 lg:flex-row lg:items-center lg:justify-between"><div><div className="flex items-center gap-2"><b>Loan #{l.id}</b><span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-bold dark:bg-slate-800">{l.status}</span></div><p className="mt-2 text-sm text-slate-500">{t.amount}: <b>{money(l.amount)}</b></p></div><div className="flex flex-wrap gap-2"><Link href={'/payments?loanId='+l.id} className="rounded-xl bg-blue-600 px-3 py-2 text-xs font-bold text-white"><CreditCard className="mr-1 inline h-3.5 w-3.5"/>{t.pay}</Link><Link href={'/agreements?loanId='+l.id} className="rounded-xl border px-3 py-2 text-xs font-bold"><FileText className="mr-1 inline h-3.5 w-3.5"/>{t.agreement}</Link><Link href={'/repayments?loanId='+l.id} className="rounded-xl border px-3 py-2 text-xs font-bold"><ShieldCheck className="mr-1 inline h-3.5 w-3.5"/>{t.schedule}</Link></div></div>)}</div>}</section>
  </main>
 </div>
}