'use client';

import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {CheckCircle2,Clock3,CreditCard,FileText,LogOut,RefreshCw,ShieldCheck,WalletCards,Calculator} from 'lucide-react';
import {generalLoanApplicationAPI,loanAPI,guarantorAPI} from '@/lib/api';
import LanguageSwitcher from '@/components/LanguageSwitcher';
import {useLanguage} from '@/lib/useLanguage';

const money=(v:any)=>new Intl.NumberFormat('sw-TZ',{style:'currency',currency:'TZS',maximumFractionDigits:0}).format(Number(v||0));
const unwrap=(r:any)=>r?.data?.data??r?.data??[];
const labels:any={sw:{title:'Dashboard ya Mkopaji',welcome:'Karibu',subtitle:'Dhibiti maombi, mikopo, marejesho na nyaraka zako.',total:'Jumla ya mikopo',active:'Mikopo inayoendelea',paid:'Imelipwa',pending:'Inasubiri',amount:'Kiasi',profile:'Wasifu',logout:'Toka',empty:'Huna mikopo bado.'},en:{title:'Borrower Dashboard',welcome:'Welcome',subtitle:'Manage your applications, loans, repayments and documents.',total:'Total loans',active:'Active loans',paid:'Paid',pending:'Pending',amount:'Amount',profile:'Profile',logout:'Logout',empty:'You have no loans yet.'}};

export default function BorrowerPage(){
 const router=useRouter();const {lang}=useLanguage();const t=labels[lang];const [user,setUser]=useState<any>(null),[applications,setApplications]=useState<any[]>([]),[loans,setLoans]=useState<any[]>([]),[guarantees,setGuarantees]=useState<any[]>([]),[loading,setLoading]=useState(true),[err,setErr]=useState('');
 const [amount,setAmount]=useState(''),[duration,setDuration]=useState(''),[purpose,setPurpose]=useState(''),[submitting,setSubmitting]=useState(false);
 const [calcAmount,setCalcAmount]=useState(''),[calcRate,setCalcRate]=useState(''),[calcMonths,setCalcMonths]=useState(''),[calcFee,setCalcFee]=useState('');
 const load=async()=>{setLoading(true);try{const [l,a,g]=await Promise.all([loanAPI.byBorrower(),generalLoanApplicationAPI.mine(),guarantorAPI.mine()]);setLoans(Array.isArray(unwrap(l))?unwrap(l):[]);setApplications(Array.isArray(unwrap(a))?unwrap(a):[]);setGuarantees(Array.isArray(unwrap(g))?unwrap(g):[]);setErr('')}catch(e:any){setErr(e?.response?.data?.message||'Imeshindikana kupakia taarifa.')}finally{setLoading(false)}};
 useEffect(()=>{const token=localStorage.getItem('token'),raw=localStorage.getItem('user');if(!token||!raw){router.push('/login');return}const u=JSON.parse(raw);if(u.role!=='BORROWER'){router.push('/dashboard');return}setUser(u);load();},[router]);
 const submit=async(e:any)=>{e.preventDefault();if(Number(amount)<=0||Number(duration)<=0||!purpose.trim())return;setSubmitting(true);setErr('');try{await generalLoanApplicationAPI.submit({amount:Number(amount),duration:Number(duration),purpose:purpose.trim(),termsAccepted:false});setAmount('');setDuration('');setPurpose('');await load();setErr(lang==='sw'?'Ombi limetumwa. Mkopeshaji ata-review na kuandaa offer kulingana na ombi lako.':'Application sent. The lender will review it and prepare an offer based on your request.');}catch(e:any){setErr(e?.response?.data?.message||'Ombi halikutumwa.')}finally{setSubmitting(false)}};
 const calc=useMemo(()=>{const p=Number(calcAmount),r=Number(calcRate),m=Number(calcMonths),f=Number(calcFee||0);if(p<=0||r<0||m<=0)return null;const interest=p*r/100*(m/12);const total=p+interest+f;return {interest,total,installment:total/m};},[calcAmount,calcRate,calcMonths,calcFee]);
 const stats={total:loans.length,active:loans.filter(x=>['APPROVED','DISBURSED'].includes(x.status)).length,paid:loans.filter(x=>x.status==='PAID').length,pending:loans.filter(x=>x.status==='PENDING').length};
 const activeLoans=loans.filter(x=>['APPROVED','DISBURSED','DEFAULTED'].includes(x.status));
 const nextDue=activeLoans.filter(x=>x.nextDueDate).sort((a,b)=>String(a.nextDueDate).localeCompare(String(b.nextDueDate)))[0];
 const daysRemaining=nextDue?.nextDueDate?Math.ceil((new Date(nextDue.nextDueDate+'T23:59:59').getTime()-Date.now())/86400000):null;
 const logout=()=>{localStorage.clear();document.cookie='token=; path=/; max-age=0';router.push('/login')};
 if(!user)return null;
 return <div className="min-h-screen bg-slate-50 text-slate-900 dark:bg-slate-950 dark:text-white">
  <nav className="sticky top-0 z-40 border-b bg-white/95 px-4 py-3 backdrop-blur dark:border-slate-800 dark:bg-slate-900/95"><div className="mx-auto flex max-w-7xl items-center justify-between"><Link href="/" className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-blue-600 text-xl text-white">💰</div><div><b>JmkLoanApp</b><div className="text-[10px] text-slate-500">{t.title}</div></div></Link><div className="flex items-center gap-2"><LanguageSwitcher/><Link href="/profile" className="hidden rounded-xl px-3 py-2 text-sm font-semibold sm:block">{t.profile}</Link><button onClick={logout} className="flex items-center gap-2 rounded-xl px-3 py-2 text-sm font-semibold text-red-600"><LogOut className="h-4 w-4"/>{t.logout}</button></div></div></nav>
  <main className="mx-auto max-w-7xl space-y-6 p-4 sm:p-6">
   <div className="flex flex-wrap gap-2"><Link href="/borrower/apply" className="rounded-xl bg-blue-600 px-4 py-2 text-sm font-black text-white">➕ Omba Mkopo</Link><Link href="/loan-offer" className="rounded-xl border bg-white px-4 py-2 text-sm font-black dark:bg-slate-900">Offers</Link><Link href="/agreements" className="rounded-xl border bg-white px-4 py-2 text-sm font-black dark:bg-slate-900">Agreements</Link><Link href="/payments" className="rounded-xl border bg-white px-4 py-2 text-sm font-black dark:bg-slate-900">Lipa</Link><Link href="/repayments" className="rounded-xl border bg-white px-4 py-2 text-sm font-black dark:bg-slate-900">Ratiba</Link></div>
   <section className="rounded-3xl bg-gradient-to-br from-blue-700 to-slate-900 p-6 text-white shadow-xl"><p className="text-sm text-blue-100">{t.welcome}</p><h1 className="text-3xl font-black">{user.fullName}</h1><p className="mt-2 text-sm text-blue-100">{t.subtitle}</p></section>
   <section className="rounded-3xl border border-blue-200 bg-white p-6 shadow-sm dark:border-blue-900 dark:bg-slate-900"><div className="flex items-start gap-3"><div className="rounded-xl bg-blue-50 p-3 text-blue-600"><WalletCards className="h-5 w-5"/></div><div><h2 className="text-xl font-black">Omba Mkopo</h2><p className="text-sm text-slate-500">Huhitaji kuchagua product. Eleza kiasi unachohitaji, muda na matumizi ya fedha; lender ataandaa offer kulingana na tathmini yake.</p></div></div>
    <form onSubmit={submit} className="mt-5 grid gap-3 md:grid-cols-3"><label className="text-sm font-bold">Kiasi (TZS)<input required min="1" type="number" value={amount} onChange={e=>setAmount(e.target.value)} className="mt-1 w-full rounded-xl border p-3 dark:border-slate-700 dark:bg-slate-950"/></label><label className="text-sm font-bold">Muda (siku)<input required min="1" type="number" value={duration} onChange={e=>setDuration(e.target.value)} className="mt-1 w-full rounded-xl border p-3 dark:border-slate-700 dark:bg-slate-950"/></label><label className="text-sm font-bold">Unahitaji kwa nini?<input required maxLength={500} value={purpose} onChange={e=>setPurpose(e.target.value)} className="mt-1 w-full rounded-xl border p-3 dark:border-slate-700 dark:bg-slate-950"/></label><button disabled={submitting} className="rounded-xl bg-blue-600 px-4 py-3 font-black text-white md:col-span-3 disabled:opacity-50">{submitting?'Inatuma...':'Tuma ombi la mkopo'}</button></form>
   </section>
   <section className="rounded-3xl border border-emerald-200 bg-white p-6 shadow-sm dark:border-emerald-900 dark:bg-slate-900"><div className="flex items-center gap-3"><div className="rounded-xl bg-emerald-50 p-3 text-emerald-600"><Calculator className="h-5 w-5"/></div><div><h2 className="text-xl font-black">Calculator ya Fedha/Mkopo</h2><p className="text-sm text-slate-500">Makadirio ya riba, ada, jumla ya kurejesha na installment bila kuchagua product.</p></div></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><input type="number" min="1" placeholder="Kiasi" value={calcAmount} onChange={e=>setCalcAmount(e.target.value)} className="rounded-xl border p-3 dark:border-slate-700 dark:bg-slate-950"/><input type="number" min="0" step="0.01" placeholder="Riba % kwa mwaka" value={calcRate} onChange={e=>setCalcRate(e.target.value)} className="rounded-xl border p-3 dark:border-slate-700 dark:bg-slate-950"/><input type="number" min="1" placeholder="Miezi" value={calcMonths} onChange={e=>setCalcMonths(e.target.value)} className="rounded-xl border p-3 dark:border-slate-700 dark:bg-slate-950"/><input type="number" min="0" placeholder="Ada" value={calcFee} onChange={e=>setCalcFee(e.target.value)} className="rounded-xl border p-3 dark:border-slate-700 dark:bg-slate-950"/></div>{calc&&<div className="mt-5 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl bg-slate-50 p-4 dark:bg-slate-950"><span className="text-xs text-slate-500">Riba</span><div className="text-lg font-black">{money(calc.interest)}</div></div><div className="rounded-2xl bg-slate-50 p-4 dark:bg-slate-950"><span className="text-xs text-slate-500">Jumla</span><div className="text-lg font-black">{money(calc.total)}</div></div><div className="rounded-2xl bg-blue-50 p-4 text-blue-700 dark:bg-blue-950"><span className="text-xs">Installment ya mwezi</span><div className="text-lg font-black">{money(calc.installment)}</div></div></div>}</section>
   <section className="grid gap-4 lg:grid-cols-3">
    <div className="rounded-3xl border border-amber-200 bg-amber-50 p-5 dark:border-amber-900 dark:bg-amber-950/30"><div className="text-xs font-black uppercase tracking-wider text-amber-700">Deni linalofuata</div><div className="mt-2 text-2xl font-black">{nextDue?money(nextDue.amount||0):'—'}</div><div className="mt-1 text-sm text-slate-600 dark:text-slate-300">{nextDue?'Loan #'+nextDue.id+' · '+nextDue.nextDueDate:'Hakuna tarehe ya malipo iliyopangwa'}</div></div>
    <div className="rounded-3xl border border-blue-200 bg-blue-50 p-5 dark:border-blue-900 dark:bg-blue-950/30"><div className="text-xs font-black uppercase tracking-wider text-blue-700">Siku zilizobaki</div><div className="mt-2 text-3xl font-black">{daysRemaining===null?'—':Math.abs(daysRemaining)}</div><div className="mt-1 text-sm text-slate-600 dark:text-slate-300">{daysRemaining===null?'Hakuna loan active':daysRemaining<0?'siku zimepita tangu due date':'hadi due date'}</div></div>
    <div className="rounded-3xl border border-emerald-200 bg-emerald-50 p-5 dark:border-emerald-900 dark:bg-emerald-950/30"><div className="text-xs font-black uppercase tracking-wider text-emerald-700">Hatua ya sasa</div><div className="mt-2 text-xl font-black">{nextDue?.status||'Hakuna loan active'}</div><div className="mt-1 text-sm text-slate-600 dark:text-slate-300">Lipa, soma agreement au fungua ratiba.</div></div>
   </section>
   <section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[[t.total,stats.total,FileText],[t.active,stats.active,WalletCards],[t.pending,stats.pending,Clock3],[t.paid,stats.paid,CheckCircle2]].map(([x,v,I]:any)=><div className="rounded-2xl border bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900" key={x}><I className="h-5 w-5 text-blue-600"/><div className="mt-3 text-3xl font-black">{v}</div><div className="text-sm text-slate-500">{x}</div></div>)}</section>
   {err&&<div className="rounded-2xl border border-blue-200 bg-blue-50 p-4 text-sm text-blue-800">{err}</div>}
   <section className="rounded-3xl border bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="border-b p-5 dark:border-slate-800"><h2 className="font-black">Maombi yangu</h2><p className="text-sm text-slate-500">Ombi linaanzia bila product; offer huandaliwa baada ya lender kulipitia.</p></div>{applications.length===0?<div className="p-6 text-sm text-slate-500">Hujaomba mkopo bado.</div>:<div className="divide-y dark:divide-slate-800">{applications.map(a=><div key={a.id} className="flex flex-col gap-2 p-5 sm:flex-row sm:items-center sm:justify-between"><div><b>Application #{a.id}</b><p className="text-sm text-slate-500">{money(a.amount)} · {a.duration} {a.durationUnit||'DAYS'} · {a.purpose}</p></div><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold dark:bg-slate-800">{a.status}</span>{a.status==='SUBMITTED'&&<span className="text-xs font-semibold text-amber-700">Lender hajaanza review</span>}{a.status==='UNDER_REVIEW'&&!a.termsAccepted&&<Link href="/loan-offer" className="rounded-lg bg-blue-600 px-3 py-1 text-xs font-bold text-white">Angalia Offer</Link>}{a.status==='CONVERTED'&&<Link href="/agreements" className="rounded-lg bg-emerald-600 px-3 py-1 text-xs font-bold text-white">Fungua Agreement</Link>}</div></div>)}</div>}</section>
   <section className="rounded-3xl border bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="border-b p-5 dark:border-slate-800"><h2 className="font-black">Mikopo yangu</h2></div>{loading?<div className="p-10 text-center text-sm text-slate-500">Inapakia...</div>:loans.length===0?<div className="p-10 text-center text-sm text-slate-500">{t.empty}</div>:<div className="divide-y dark:divide-slate-800">{loans.map(l=><div key={l.id} className="flex flex-col gap-4 p-5 lg:flex-row lg:items-center lg:justify-between"><div><div className="flex items-center gap-2"><b>Loan #{l.id}</b><span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-bold dark:bg-slate-800">{l.status}</span></div><p className="mt-2 text-sm text-slate-500">{t.amount}: <b>{money(l.amount)}</b> · Jumla ya kurejesha: <b>{money(l.totalRepayment)}</b></p></div><div className="flex flex-wrap gap-2"><Link href={'/payments?loanId='+l.id} className="rounded-xl bg-blue-600 px-3 py-2 text-xs font-bold text-white"><CreditCard className="mr-1 inline h-3.5 w-3.5"/>Lipa</Link><Link href={'/agreements?loanId='+l.id} className="rounded-xl border px-3 py-2 text-xs font-bold"><FileText className="mr-1 inline h-3.5 w-3.5"/>Agreement</Link><Link href={'/repayments?loanId='+l.id} className="rounded-xl border px-3 py-2 text-xs font-bold"><ShieldCheck className="mr-1 inline h-3.5 w-3.5"/>Ratiba</Link></div></div>)}</div>}</section>
   <section className="rounded-3xl border bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="border-b p-5 dark:border-slate-800"><h2 className="font-black">Maendeleo ya udhamini</h2></div><div className="grid gap-3 p-5 md:grid-cols-2">{loans.map(l=>{const g=guarantees.find(x=>x.loan?.id===l.id||x.loanId===l.id);return <div key={l.id} className="rounded-2xl border p-4 dark:border-slate-800"><div className="flex justify-between"><b>Loan #{l.id}</b><span className="text-xs font-bold">{g?.status||'WAITING'}</span></div><p className="mt-1 text-sm text-slate-500">{g?.guarantor?.fullName||'Mdhamini bado hajapangiwa'}</p></div>})}</div></section>
  </main>
 </div>;
}
